/*
 * $Source$
 * $Date$
 * $Revision$
 *
 * Copyright (C) 1998, Hoylen Sue.  All Rights Reserved.
 * <h.sue@ieee.org>
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Refer to
 * the supplied license for more details.
 *
 * Generated by Zebulun ASN1tojava: 1998-09-08 03:20:30 UTC
 */

//----------------------------------------------------------------

package z3950.ESFormat_CIP2_4Order;
import asn1.*;
import z3950.v3.InternationalString;
import z3950.v3.OtherInformation;

//================================================================
/**
 * Class for representing a <code>OriginPartToKeep</code> from <code>CIP-Order-ES</code>
 *
 * <pre>
 * OriginPartToKeep ::=
 * SEQUENCE {
 *   action [1] IMPLICIT INTEGER
 *   orderId [2] EXPLICIT InternationalString OPTIONAL
 *   orderSpecification [3] EXPLICIT OrderSpecification OPTIONAL
 *   statusUpdateOption [4] EXPLICIT StatusUpdateOption OPTIONAL
 *   userInformation [5] EXPLICIT UserInformation OPTIONAL
 *   otherInfo [6] EXPLICIT OtherInformation OPTIONAL
 * }
 * </pre>
 *
 * @version	$Release$ $Date$
 */

//----------------------------------------------------------------

public final class OriginPartToKeep extends ASN1Any
{

  public final static String VERSION = "Copyright (C) Hoylen Sue, 1998. 199809080320Z";

//----------------------------------------------------------------
/**
 * Default constructor for a OriginPartToKeep.
 */

public
OriginPartToKeep()
{
}

//----------------------------------------------------------------
/**
 * Constructor for a OriginPartToKeep from a BER encoding.
 * <p>
 *
 * @param ber the BER encoding.
 * @param check_tag will check tag if true, use false
 *         if the BER has been implicitly tagged. You should
 *         usually be passing true.
 * @exception	ASN1Exception if the BER encoding is bad.
 */

public
OriginPartToKeep(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  super(ber, check_tag);
}

//----------------------------------------------------------------
/**
 * Initializing object from a BER encoding.
 * This method is for internal use only. You should use
 * the constructor that takes a BEREncoding.
 *
 * @param ber the BER to decode.
 * @param check_tag if the tag should be checked.
 * @exception ASN1Exception if the BER encoding is bad.
 */

public void
ber_decode(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  // OriginPartToKeep should be encoded by a constructed BER

  BERConstructed ber_cons;
  try {
    ber_cons = (BERConstructed) ber;
  } catch (ClassCastException e) {
    throw new ASN1EncodingException
      ("Zebulun OriginPartToKeep: bad BER form\n");
  }

  // Prepare to decode the components

  int num_parts = ber_cons.number_components();
  int part = 0;
  BEREncoding p;
  BERConstructed tagged;

  // Decoding: action [1] IMPLICIT INTEGER

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun OriginPartToKeep: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() != 1 ||
      p.tag_type_get() != BEREncoding.CONTEXT_SPECIFIC_TAG)
    throw new ASN1EncodingException
      ("Zebulun OriginPartToKeep: bad tag in s_action\n");

  s_action = new ASN1Integer(p, false);
  part++;

  // Remaining elements are optional, set variables
  // to null (not present) so can return at end of BER

  s_orderId = null;
  s_orderSpecification = null;
  s_statusUpdateOption = null;
  s_userInformation = null;
  s_otherInfo = null;

  // Decoding: orderId [2] EXPLICIT InternationalString OPTIONAL

  if (num_parts <= part) {
    return; // no more data, but ok (rest is optional)
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 2 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    try {
      tagged = (BERConstructed) p;
    } catch (ClassCastException e) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_orderId tag bad\n");
    }
    if (tagged.number_components() != 1) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_orderId tag bad\n");
    }

    s_orderId = new InternationalString(tagged.elementAt(0), true);
    part++;
  }

  // Decoding: orderSpecification [3] EXPLICIT OrderSpecification OPTIONAL

  if (num_parts <= part) {
    return; // no more data, but ok (rest is optional)
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 3 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    try {
      tagged = (BERConstructed) p;
    } catch (ClassCastException e) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_orderSpecification tag bad\n");
    }
    if (tagged.number_components() != 1) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_orderSpecification tag bad\n");
    }

    s_orderSpecification = new OrderSpecification(tagged.elementAt(0), true);
    part++;
  }

  // Decoding: statusUpdateOption [4] EXPLICIT StatusUpdateOption OPTIONAL

  if (num_parts <= part) {
    return; // no more data, but ok (rest is optional)
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 4 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    try {
      tagged = (BERConstructed) p;
    } catch (ClassCastException e) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_statusUpdateOption tag bad\n");
    }
    if (tagged.number_components() != 1) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_statusUpdateOption tag bad\n");
    }

    s_statusUpdateOption = new StatusUpdateOption(tagged.elementAt(0), true);
    part++;
  }

  // Decoding: userInformation [5] EXPLICIT UserInformation OPTIONAL

  if (num_parts <= part) {
    return; // no more data, but ok (rest is optional)
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 5 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    try {
      tagged = (BERConstructed) p;
    } catch (ClassCastException e) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_userInformation tag bad\n");
    }
    if (tagged.number_components() != 1) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_userInformation tag bad\n");
    }

    s_userInformation = new UserInformation(tagged.elementAt(0), true);
    part++;
  }

  // Decoding: otherInfo [6] EXPLICIT OtherInformation OPTIONAL

  if (num_parts <= part) {
    return; // no more data, but ok (rest is optional)
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 6 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    try {
      tagged = (BERConstructed) p;
    } catch (ClassCastException e) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_otherInfo tag bad\n");
    }
    if (tagged.number_components() != 1) {
      throw new ASN1EncodingException
        ("Zebulun OriginPartToKeep: bad BER encoding: s_otherInfo tag bad\n");
    }

    s_otherInfo = new OtherInformation(tagged.elementAt(0), true);
    part++;
  }

  // Should not be any more parts

  if (part < num_parts) {
    throw new ASN1Exception("Zebulun OriginPartToKeep: bad BER: extra data " + part + "/" + num_parts + " processed");
  }
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of the OriginPartToKeep.
 *
 * @exception	ASN1Exception Invalid or cannot be encoded.
 * @return	The BER encoding.
 */

public BEREncoding
ber_encode()
       throws ASN1Exception
{
  return ber_encode(BEREncoding.UNIVERSAL_TAG, ASN1Sequence.TAG);
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of OriginPartToKeep, implicitly tagged.
 *
 * @param tag_type	The type of the implicit tag.
 * @param tag	The implicit tag.
 * @return	The BER encoding of the object.
 * @exception	ASN1Exception When invalid or cannot be encoded.
 * @see asn1.BEREncoding#UNIVERSAL_TAG
 * @see asn1.BEREncoding#APPLICATION_TAG
 * @see asn1.BEREncoding#CONTEXT_SPECIFIC_TAG
 * @see asn1.BEREncoding#PRIVATE_TAG
 */

public BEREncoding
ber_encode(int tag_type, int tag)
       throws ASN1Exception
{
  // Calculate the number of fields in the encoding

  int num_fields = 1; // number of mandatories
  if (s_orderId != null)
    num_fields++;
  if (s_orderSpecification != null)
    num_fields++;
  if (s_statusUpdateOption != null)
    num_fields++;
  if (s_userInformation != null)
    num_fields++;
  if (s_otherInfo != null)
    num_fields++;

  // Encode it

  BEREncoding fields[] = new BEREncoding[num_fields];
  int x = 0;
  BEREncoding enc[];

  // Encoding s_action: INTEGER 

  fields[x++] = s_action.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 1);

  // Encoding s_orderId: InternationalString OPTIONAL

  if (s_orderId != null) {
    enc = new BEREncoding[1];
    enc[0] = s_orderId.ber_encode();
    fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 2, enc);
  }

  // Encoding s_orderSpecification: OrderSpecification OPTIONAL

  if (s_orderSpecification != null) {
    enc = new BEREncoding[1];
    enc[0] = s_orderSpecification.ber_encode();
    fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 3, enc);
  }

  // Encoding s_statusUpdateOption: StatusUpdateOption OPTIONAL

  if (s_statusUpdateOption != null) {
    enc = new BEREncoding[1];
    enc[0] = s_statusUpdateOption.ber_encode();
    fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 4, enc);
  }

  // Encoding s_userInformation: UserInformation OPTIONAL

  if (s_userInformation != null) {
    enc = new BEREncoding[1];
    enc[0] = s_userInformation.ber_encode();
    fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 5, enc);
  }

  // Encoding s_otherInfo: OtherInformation OPTIONAL

  if (s_otherInfo != null) {
    enc = new BEREncoding[1];
    enc[0] = s_otherInfo.ber_encode();
    fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 6, enc);
  }

  return new BERConstructed(tag_type, tag, fields);
}

//----------------------------------------------------------------
/**
 * Returns a new String object containing a text representing
 * of the OriginPartToKeep. 
 */

public String
toString()
{
  StringBuffer str = new StringBuffer("{");
  int outputted = 0;

  str.append("action ");
  str.append(s_action);
  outputted++;

  if (s_orderId != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("orderId ");
    str.append(s_orderId);
    outputted++;
  }

  if (s_orderSpecification != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("orderSpecification ");
    str.append(s_orderSpecification);
    outputted++;
  }

  if (s_statusUpdateOption != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("statusUpdateOption ");
    str.append(s_statusUpdateOption);
    outputted++;
  }

  if (s_userInformation != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("userInformation ");
    str.append(s_userInformation);
    outputted++;
  }

  if (s_otherInfo != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("otherInfo ");
    str.append(s_otherInfo);
    outputted++;
  }

  str.append("}");

  return str.toString();
}

//----------------------------------------------------------------
/*
 * Internal variables for class.
 */

public ASN1Integer s_action;
public InternationalString s_orderId; // optional
public OrderSpecification s_orderSpecification; // optional
public StatusUpdateOption s_statusUpdateOption; // optional
public UserInformation s_userInformation; // optional
public OtherInformation s_otherInfo; // optional

//----------------------------------------------------------------
/*
 * Enumerated constants for class.
 */

// Enumerated constants for action
public static final int E_orderEstimate = 1;
public static final int E_orderQuoteAndSubmit = 2;
public static final int E_orderMonitor = 3;
public static final int E_orderCancel = 4;

} // OriginPartToKeep

//----------------------------------------------------------------
//EOF
