/*
 * $Source$
 * $Date$
 * $Revision$
 *
 * Copyright (C) 1998, Hoylen Sue.  All Rights Reserved.
 * <h.sue@ieee.org>
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Refer to
 * the supplied license for more details.
 *
 * Generated by Zebulun ASN1tojava: 1998-09-08 03:15:27 UTC
 */

//----------------------------------------------------------------

package z3950.ESFormat_Update;
import asn1.*;
import z3950.v3.DiagRec;
import z3950.v3.InternationalString;

//================================================================
/**
 * Class for representing a <code>SuppliedRecords1</code> from <code>ESFormat-Update</code>
 *
 * <pre>
 * SuppliedRecords1 ::=
 * SEQUENCE {
 *   recordId [1] EXPLICIT SuppliedRecords_recordId OPTIONAL
 *   supplementalId [2] EXPLICIT SuppliedRecords_supplementalId OPTIONAL
 *   correlationInfo [3] IMPLICIT CorrelationInfo OPTIONAL
 *   record [4] IMPLICIT EXTERNAL
 * }
 * </pre>
 *
 * @version	$Release$ $Date$
 */

//----------------------------------------------------------------

public final class SuppliedRecords1 extends ASN1Any
{

  public final static String VERSION = "Copyright (C) Hoylen Sue, 1998. 199809080315Z";

//----------------------------------------------------------------
/**
 * Default constructor for a SuppliedRecords1.
 */

public
SuppliedRecords1()
{
}

//----------------------------------------------------------------
/**
 * Constructor for a SuppliedRecords1 from a BER encoding.
 * <p>
 *
 * @param ber the BER encoding.
 * @param check_tag will check tag if true, use false
 *         if the BER has been implicitly tagged. You should
 *         usually be passing true.
 * @exception	ASN1Exception if the BER encoding is bad.
 */

public
SuppliedRecords1(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  super(ber, check_tag);
}

//----------------------------------------------------------------
/**
 * Initializing object from a BER encoding.
 * This method is for internal use only. You should use
 * the constructor that takes a BEREncoding.
 *
 * @param ber the BER to decode.
 * @param check_tag if the tag should be checked.
 * @exception ASN1Exception if the BER encoding is bad.
 */

public void
ber_decode(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  // SuppliedRecords1 should be encoded by a constructed BER

  BERConstructed ber_cons;
  try {
    ber_cons = (BERConstructed) ber;
  } catch (ClassCastException e) {
    throw new ASN1EncodingException
      ("Zebulun SuppliedRecords1: bad BER form\n");
  }

  // Prepare to decode the components

  int num_parts = ber_cons.number_components();
  int part = 0;
  BEREncoding p;
  BERConstructed tagged;

  // Decoding: recordId [1] EXPLICIT SuppliedRecords_recordId OPTIONAL

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun SuppliedRecords1: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 1 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    try {
      tagged = (BERConstructed) p;
    } catch (ClassCastException e) {
      throw new ASN1EncodingException
        ("Zebulun SuppliedRecords1: bad BER encoding: s_recordId tag bad\n");
    }
    if (tagged.number_components() != 1) {
      throw new ASN1EncodingException
        ("Zebulun SuppliedRecords1: bad BER encoding: s_recordId tag bad\n");
    }

    s_recordId = new SuppliedRecords_recordId(tagged.elementAt(0), true);
    part++;
  }

  // Decoding: supplementalId [2] EXPLICIT SuppliedRecords_supplementalId OPTIONAL

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun SuppliedRecords1: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 2 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    try {
      tagged = (BERConstructed) p;
    } catch (ClassCastException e) {
      throw new ASN1EncodingException
        ("Zebulun SuppliedRecords1: bad BER encoding: s_supplementalId tag bad\n");
    }
    if (tagged.number_components() != 1) {
      throw new ASN1EncodingException
        ("Zebulun SuppliedRecords1: bad BER encoding: s_supplementalId tag bad\n");
    }

    s_supplementalId = new SuppliedRecords_supplementalId(tagged.elementAt(0), true);
    part++;
  }

  // Decoding: correlationInfo [3] IMPLICIT CorrelationInfo OPTIONAL

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun SuppliedRecords1: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 3 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    s_correlationInfo = new CorrelationInfo(p, false);
    part++;
  }

  // Decoding: record [4] IMPLICIT EXTERNAL

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun SuppliedRecords1: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() != 4 ||
      p.tag_type_get() != BEREncoding.CONTEXT_SPECIFIC_TAG)
    throw new ASN1EncodingException
      ("Zebulun SuppliedRecords1: bad tag in s_record\n");

  s_record = new ASN1External(p, false);
  part++;

  // Should not be any more parts

  if (part < num_parts) {
    throw new ASN1Exception("Zebulun SuppliedRecords1: bad BER: extra data " + part + "/" + num_parts + " processed");
  }
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of the SuppliedRecords1.
 *
 * @exception	ASN1Exception Invalid or cannot be encoded.
 * @return	The BER encoding.
 */

public BEREncoding
ber_encode()
       throws ASN1Exception
{
  return ber_encode(BEREncoding.UNIVERSAL_TAG, ASN1Sequence.TAG);
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of SuppliedRecords1, implicitly tagged.
 *
 * @param tag_type	The type of the implicit tag.
 * @param tag	The implicit tag.
 * @return	The BER encoding of the object.
 * @exception	ASN1Exception When invalid or cannot be encoded.
 * @see asn1.BEREncoding#UNIVERSAL_TAG
 * @see asn1.BEREncoding#APPLICATION_TAG
 * @see asn1.BEREncoding#CONTEXT_SPECIFIC_TAG
 * @see asn1.BEREncoding#PRIVATE_TAG
 */

public BEREncoding
ber_encode(int tag_type, int tag)
       throws ASN1Exception
{
  // Calculate the number of fields in the encoding

  int num_fields = 1; // number of mandatories
  if (s_recordId != null)
    num_fields++;
  if (s_supplementalId != null)
    num_fields++;
  if (s_correlationInfo != null)
    num_fields++;

  // Encode it

  BEREncoding fields[] = new BEREncoding[num_fields];
  int x = 0;
  BEREncoding enc[];

  // Encoding s_recordId: SuppliedRecords_recordId OPTIONAL

  if (s_recordId != null) {
    enc = new BEREncoding[1];
    enc[0] = s_recordId.ber_encode();
    fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 1, enc);
  }

  // Encoding s_supplementalId: SuppliedRecords_supplementalId OPTIONAL

  if (s_supplementalId != null) {
    enc = new BEREncoding[1];
    enc[0] = s_supplementalId.ber_encode();
    fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 2, enc);
  }

  // Encoding s_correlationInfo: CorrelationInfo OPTIONAL

  if (s_correlationInfo != null) {
    fields[x++] = s_correlationInfo.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 3);
  }

  // Encoding s_record: EXTERNAL 

  fields[x++] = s_record.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 4);

  return new BERConstructed(tag_type, tag, fields);
}

//----------------------------------------------------------------
/**
 * Returns a new String object containing a text representing
 * of the SuppliedRecords1. 
 */

public String
toString()
{
  StringBuffer str = new StringBuffer("{");
  int outputted = 0;

  if (s_recordId != null) {
    str.append("recordId ");
    str.append(s_recordId);
    outputted++;
  }

  if (s_supplementalId != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("supplementalId ");
    str.append(s_supplementalId);
    outputted++;
  }

  if (s_correlationInfo != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("correlationInfo ");
    str.append(s_correlationInfo);
    outputted++;
  }

  if (0 < outputted)
    str.append(", ");
  str.append("record ");
  str.append(s_record);
  outputted++;

  str.append("}");

  return str.toString();
}

//----------------------------------------------------------------
/*
 * Internal variables for class.
 */

public SuppliedRecords_recordId s_recordId; // optional
public SuppliedRecords_supplementalId s_supplementalId; // optional
public CorrelationInfo s_correlationInfo; // optional
public ASN1External s_record;

} // SuppliedRecords1

//----------------------------------------------------------------
//EOF
