/*
 * $Source$
 * $Date$
 * $Revision$
 *
 * Copyright (C) 1998, Hoylen Sue.  All Rights Reserved.
 * <h.sue@ieee.org>
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Refer to
 * the supplied license for more details.
 *
 * Generated by Zebulun ASN1tojava: 1998-09-08 03:15:27 UTC
 */

//----------------------------------------------------------------

package z3950.ESFormat_Update;
import asn1.*;
import z3950.v3.DiagRec;
import z3950.v3.InternationalString;

//================================================================
/**
 * Class for representing a <code>SuppliedRecords_recordId</code> from <code>ESFormat-Update</code>
 *
 * <pre>
 * SuppliedRecords_recordId ::=
 * CHOICE {
 *   number [1] IMPLICIT INTEGER
 *   string [2] IMPLICIT InternationalString
 *   opaque [3] IMPLICIT OCTET STRING
 * }
 * </pre>
 *
 * @version	$Release$ $Date$
 */

//----------------------------------------------------------------

public final class SuppliedRecords_recordId extends ASN1Any
{

  public final static String VERSION = "Copyright (C) Hoylen Sue, 1998. 199809080315Z";

//----------------------------------------------------------------
/**
 * Default constructor for a SuppliedRecords_recordId.
 */

public
SuppliedRecords_recordId()
{
}

//----------------------------------------------------------------
/**
 * Constructor for a SuppliedRecords_recordId from a BER encoding.
 * <p>
 *
 * @param ber the BER encoding.
 * @param check_tag will check tag if true, use false
 *         if the BER has been implicitly tagged. You should
 *         usually be passing true.
 * @exception	ASN1Exception if the BER encoding is bad.
 */

public
SuppliedRecords_recordId(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  super(ber, check_tag);
}

//----------------------------------------------------------------
/**
 * Initializing object from a BER encoding.
 * This method is for internal use only. You should use
 * the constructor that takes a BEREncoding.
 *
 * @param ber the BER to decode.
 * @param check_tag if the tag should be checked.
 * @exception ASN1Exception if the BER encoding is bad.
 */

public void
ber_decode(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  // Null out all choices

  c_number = null;
  c_string = null;
  c_opaque = null;

  // Try choice number
  if (ber.tag_get() == 1 &&
      ber.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    c_number = new ASN1Integer(ber, false);
    return;
  }

  // Try choice string
  if (ber.tag_get() == 2 &&
      ber.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    c_string = new InternationalString(ber, false);
    return;
  }

  // Try choice opaque
  if (ber.tag_get() == 3 &&
      ber.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    c_opaque = new ASN1OctetString(ber, false);
    return;
  }

  throw new ASN1Exception("Zebulun SuppliedRecords_recordId: bad BER encoding: choice not matched");
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of SuppliedRecords_recordId.
 *
 * @return	The BER encoding.
 * @exception	ASN1Exception Invalid or cannot be encoded.
 */

public BEREncoding
ber_encode()
       throws ASN1Exception
{
  BEREncoding chosen = null;

  // Encoding choice: c_number
  if (c_number != null) {
    chosen = c_number.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 1);
  }

  // Encoding choice: c_string
  if (c_string != null) {
    if (chosen != null)
      throw new ASN1Exception("CHOICE multiply set");
    chosen = c_string.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 2);
  }

  // Encoding choice: c_opaque
  if (c_opaque != null) {
    if (chosen != null)
      throw new ASN1Exception("CHOICE multiply set");
    chosen = c_opaque.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 3);
  }

  // Check for error of having none of the choices set
  if (chosen == null)
    throw new ASN1Exception("CHOICE not set");

  return chosen;
}

//----------------------------------------------------------------

/**
 * Generating a BER encoding of the object
 * and implicitly tagging it.
 * <p>
 * This method is for internal use only. You should use
 * the ber_encode method that does not take a parameter.
 * <p>
 * This function should never be used, because this
 * production is a CHOICE.
 * It must never have an implicit tag.
 * <p>
 * An exception will be thrown if it is called.
 *
 * @param tag_type the type of the tag.
 * @param tag the tag.
 * @exception ASN1Exception if it cannot be BER encoded.
 */

public BEREncoding
ber_encode(int tag_type, int tag)
       throws ASN1Exception
{
  // This method must not be called!

  // Method is not available because this is a basic CHOICE
  // which does not have an explicit tag on it. So it is not
  // permitted to allow something else to apply an implicit
  // tag on it, otherwise the tag identifying which CHOICE
  // it is will be overwritten and lost.

  throw new ASN1EncodingException("Zebulun SuppliedRecords_recordId: cannot implicitly tag");
}

//----------------------------------------------------------------
/**
 * Returns a new String object containing a text representing
 * of the SuppliedRecords_recordId. 
 */

public String
toString()
{
  StringBuffer str = new StringBuffer("{");

  boolean found = false;

  if (c_number != null) {
    if (found)
      str.append("<ERROR: multiple CHOICE: number> ");
    found = true;
    str.append("number ");
  str.append(c_number);
  }

  if (c_string != null) {
    if (found)
      str.append("<ERROR: multiple CHOICE: string> ");
    found = true;
    str.append("string ");
  str.append(c_string);
  }

  if (c_opaque != null) {
    if (found)
      str.append("<ERROR: multiple CHOICE: opaque> ");
    found = true;
    str.append("opaque ");
  str.append(c_opaque);
  }

  str.append("}");

  return str.toString();
}

//----------------------------------------------------------------
/*
 * Internal variables for class.
 */

public ASN1Integer c_number;
public InternationalString c_string;
public ASN1OctetString c_opaque;

} // SuppliedRecords_recordId

//----------------------------------------------------------------
//EOF
