/*
 * $Source$
 * $Date$
 * $Revision$
 *
 * Copyright (C) 1998, Hoylen Sue.  All Rights Reserved.
 * <h.sue@ieee.org>
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Refer to
 * the supplied license for more details.
 *
 * Generated by Zebulun ASN1tojava: 1998-09-08 03:15:26 UTC
 */

//----------------------------------------------------------------

package z3950.ESFormat_PeriodicQuerySchedule;
import asn1.*;
import z3950.ESFormat_ExportSpec.Destination;
import z3950.ESFormat_ExportSpec.ExportSpecification;
import z3950.v3.IntUnit;
import z3950.v3.InternationalString;
import z3950.v3.Query;

//================================================================
/**
 * Class for representing a <code>TargetPart</code> from <code>ESFormat-PeriodicQuerySchedule</code>
 *
 * <pre>
 * TargetPart ::=
 * SEQUENCE {
 *   actualQuery [1] EXPLICIT Query
 *   targetStatedPeriod [2] EXPLICIT Period
 *   expiration [3] IMPLICIT GeneralizedTime OPTIONAL
 *   resultSetPackage [4] IMPLICIT InternationalString OPTIONAL
 *   lastQueryTime [5] IMPLICIT GeneralizedTime
 *   lastResultNumber [6] IMPLICIT INTEGER
 *   numberSinceModify [7] IMPLICIT INTEGER OPTIONAL
 * }
 * </pre>
 *
 * @version	$Release$ $Date$
 */

//----------------------------------------------------------------

public final class TargetPart extends ASN1Any
{

  public final static String VERSION = "Copyright (C) Hoylen Sue, 1998. 199809080315Z";

//----------------------------------------------------------------
/**
 * Default constructor for a TargetPart.
 */

public
TargetPart()
{
}

//----------------------------------------------------------------
/**
 * Constructor for a TargetPart from a BER encoding.
 * <p>
 *
 * @param ber the BER encoding.
 * @param check_tag will check tag if true, use false
 *         if the BER has been implicitly tagged. You should
 *         usually be passing true.
 * @exception	ASN1Exception if the BER encoding is bad.
 */

public
TargetPart(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  super(ber, check_tag);
}

//----------------------------------------------------------------
/**
 * Initializing object from a BER encoding.
 * This method is for internal use only. You should use
 * the constructor that takes a BEREncoding.
 *
 * @param ber the BER to decode.
 * @param check_tag if the tag should be checked.
 * @exception ASN1Exception if the BER encoding is bad.
 */

public void
ber_decode(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  // TargetPart should be encoded by a constructed BER

  BERConstructed ber_cons;
  try {
    ber_cons = (BERConstructed) ber;
  } catch (ClassCastException e) {
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad BER form\n");
  }

  // Prepare to decode the components

  int num_parts = ber_cons.number_components();
  int part = 0;
  BEREncoding p;
  BERConstructed tagged;

  // Decoding: actualQuery [1] EXPLICIT Query

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun TargetPart: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() != 1 ||
      p.tag_type_get() != BEREncoding.CONTEXT_SPECIFIC_TAG)
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad tag in s_actualQuery\n");

  try {
    tagged = (BERConstructed) p;
  } catch (ClassCastException e) {
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad BER encoding: s_actualQuery tag bad\n");
  }
  if (tagged.number_components() != 1) {
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad BER encoding: s_actualQuery tag bad\n");
  }

  s_actualQuery = new Query(tagged.elementAt(0), true);
  part++;

  // Decoding: targetStatedPeriod [2] EXPLICIT Period

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun TargetPart: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() != 2 ||
      p.tag_type_get() != BEREncoding.CONTEXT_SPECIFIC_TAG)
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad tag in s_targetStatedPeriod\n");

  try {
    tagged = (BERConstructed) p;
  } catch (ClassCastException e) {
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad BER encoding: s_targetStatedPeriod tag bad\n");
  }
  if (tagged.number_components() != 1) {
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad BER encoding: s_targetStatedPeriod tag bad\n");
  }

  s_targetStatedPeriod = new Period(tagged.elementAt(0), true);
  part++;

  // Decoding: expiration [3] IMPLICIT GeneralizedTime OPTIONAL

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun TargetPart: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 3 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    s_expiration = new ASN1GeneralizedTime(p, false);
    part++;
  }

  // Decoding: resultSetPackage [4] IMPLICIT InternationalString OPTIONAL

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun TargetPart: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 4 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    s_resultSetPackage = new InternationalString(p, false);
    part++;
  }

  // Decoding: lastQueryTime [5] IMPLICIT GeneralizedTime

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun TargetPart: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() != 5 ||
      p.tag_type_get() != BEREncoding.CONTEXT_SPECIFIC_TAG)
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad tag in s_lastQueryTime\n");

  s_lastQueryTime = new ASN1GeneralizedTime(p, false);
  part++;

  // Decoding: lastResultNumber [6] IMPLICIT INTEGER

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun TargetPart: incomplete");
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() != 6 ||
      p.tag_type_get() != BEREncoding.CONTEXT_SPECIFIC_TAG)
    throw new ASN1EncodingException
      ("Zebulun TargetPart: bad tag in s_lastResultNumber\n");

  s_lastResultNumber = new ASN1Integer(p, false);
  part++;

  // Remaining elements are optional, set variables
  // to null (not present) so can return at end of BER

  s_numberSinceModify = null;

  // Decoding: numberSinceModify [7] IMPLICIT INTEGER OPTIONAL

  if (num_parts <= part) {
    return; // no more data, but ok (rest is optional)
  }
  p = ber_cons.elementAt(part);

  if (p.tag_get() == 7 &&
      p.tag_type_get() == BEREncoding.CONTEXT_SPECIFIC_TAG) {
    s_numberSinceModify = new ASN1Integer(p, false);
    part++;
  }

  // Should not be any more parts

  if (part < num_parts) {
    throw new ASN1Exception("Zebulun TargetPart: bad BER: extra data " + part + "/" + num_parts + " processed");
  }
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of the TargetPart.
 *
 * @exception	ASN1Exception Invalid or cannot be encoded.
 * @return	The BER encoding.
 */

public BEREncoding
ber_encode()
       throws ASN1Exception
{
  return ber_encode(BEREncoding.UNIVERSAL_TAG, ASN1Sequence.TAG);
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of TargetPart, implicitly tagged.
 *
 * @param tag_type	The type of the implicit tag.
 * @param tag	The implicit tag.
 * @return	The BER encoding of the object.
 * @exception	ASN1Exception When invalid or cannot be encoded.
 * @see asn1.BEREncoding#UNIVERSAL_TAG
 * @see asn1.BEREncoding#APPLICATION_TAG
 * @see asn1.BEREncoding#CONTEXT_SPECIFIC_TAG
 * @see asn1.BEREncoding#PRIVATE_TAG
 */

public BEREncoding
ber_encode(int tag_type, int tag)
       throws ASN1Exception
{
  // Calculate the number of fields in the encoding

  int num_fields = 4; // number of mandatories
  if (s_expiration != null)
    num_fields++;
  if (s_resultSetPackage != null)
    num_fields++;
  if (s_numberSinceModify != null)
    num_fields++;

  // Encode it

  BEREncoding fields[] = new BEREncoding[num_fields];
  int x = 0;
  BEREncoding enc[];

  // Encoding s_actualQuery: Query 

  enc = new BEREncoding[1];
  enc[0] = s_actualQuery.ber_encode();
  fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 1, enc);

  // Encoding s_targetStatedPeriod: Period 

  enc = new BEREncoding[1];
  enc[0] = s_targetStatedPeriod.ber_encode();
  fields[x++] = new BERConstructed(BEREncoding.CONTEXT_SPECIFIC_TAG, 2, enc);

  // Encoding s_expiration: GeneralizedTime OPTIONAL

  if (s_expiration != null) {
    fields[x++] = s_expiration.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 3);
  }

  // Encoding s_resultSetPackage: InternationalString OPTIONAL

  if (s_resultSetPackage != null) {
    fields[x++] = s_resultSetPackage.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 4);
  }

  // Encoding s_lastQueryTime: GeneralizedTime 

  fields[x++] = s_lastQueryTime.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 5);

  // Encoding s_lastResultNumber: INTEGER 

  fields[x++] = s_lastResultNumber.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 6);

  // Encoding s_numberSinceModify: INTEGER OPTIONAL

  if (s_numberSinceModify != null) {
    fields[x++] = s_numberSinceModify.ber_encode(BEREncoding.CONTEXT_SPECIFIC_TAG, 7);
  }

  return new BERConstructed(tag_type, tag, fields);
}

//----------------------------------------------------------------
/**
 * Returns a new String object containing a text representing
 * of the TargetPart. 
 */

public String
toString()
{
  StringBuffer str = new StringBuffer("{");
  int outputted = 0;

  str.append("actualQuery ");
  str.append(s_actualQuery);
  outputted++;

  if (0 < outputted)
    str.append(", ");
  str.append("targetStatedPeriod ");
  str.append(s_targetStatedPeriod);
  outputted++;

  if (s_expiration != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("expiration ");
    str.append(s_expiration);
    outputted++;
  }

  if (s_resultSetPackage != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("resultSetPackage ");
    str.append(s_resultSetPackage);
    outputted++;
  }

  if (0 < outputted)
    str.append(", ");
  str.append("lastQueryTime ");
  str.append(s_lastQueryTime);
  outputted++;

  if (0 < outputted)
    str.append(", ");
  str.append("lastResultNumber ");
  str.append(s_lastResultNumber);
  outputted++;

  if (s_numberSinceModify != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("numberSinceModify ");
    str.append(s_numberSinceModify);
    outputted++;
  }

  str.append("}");

  return str.toString();
}

//----------------------------------------------------------------
/*
 * Internal variables for class.
 */

public Query s_actualQuery;
public Period s_targetStatedPeriod;
public ASN1GeneralizedTime s_expiration; // optional
public InternationalString s_resultSetPackage; // optional
public ASN1GeneralizedTime s_lastQueryTime;
public ASN1Integer s_lastResultNumber;
public ASN1Integer s_numberSinceModify; // optional

} // TargetPart

//----------------------------------------------------------------
//EOF
