/*
 * $Source$
 * $Date$
 * $Revision$
 *
 * Copyright (C) 1998, Hoylen Sue.  All Rights Reserved.
 * <h.sue@ieee.org>
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  Refer to
 * the supplied license for more details.
 *
 * Generated by Zebulun ASN1tojava: 1998-09-08 03:14:27 UTC
 */

//----------------------------------------------------------------

package z3950.v2;
import asn1.*;


//================================================================
/**
 * Class for representing a <code>PresentResponse</code> from <code>IR</code>
 *
 * <pre>
 * PresentResponse ::=
 * SEQUENCE {
 *   referenceId ReferenceId OPTIONAL
 *   numberOfRecordsReturned NumberOfRecordsReturned
 *   nextResultSetPosition NextResultSetPosition
 *   presentStatus PresentStatus
 *   databaseOrDiagnosticRecords Records OPTIONAL
 * }
 * </pre>
 *
 * @version	$Release$ $Date$
 */

//----------------------------------------------------------------

public final class PresentResponse extends ASN1Any
{

  public final static String VERSION = "Copyright (C) Hoylen Sue, 1998. 199809080314Z";

//----------------------------------------------------------------
/**
 * Default constructor for a PresentResponse.
 */

public
PresentResponse()
{
}

//----------------------------------------------------------------
/**
 * Constructor for a PresentResponse from a BER encoding.
 * <p>
 *
 * @param ber the BER encoding.
 * @param check_tag will check tag if true, use false
 *         if the BER has been implicitly tagged. You should
 *         usually be passing true.
 * @exception	ASN1Exception if the BER encoding is bad.
 */

public
PresentResponse(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  super(ber, check_tag);
}

//----------------------------------------------------------------
/**
 * Initializing object from a BER encoding.
 * This method is for internal use only. You should use
 * the constructor that takes a BEREncoding.
 *
 * @param ber the BER to decode.
 * @param check_tag if the tag should be checked.
 * @exception ASN1Exception if the BER encoding is bad.
 */

public void
ber_decode(BEREncoding ber, boolean check_tag)
       throws ASN1Exception
{
  // PresentResponse should be encoded by a constructed BER

  BERConstructed ber_cons;
  try {
    ber_cons = (BERConstructed) ber;
  } catch (ClassCastException e) {
    throw new ASN1EncodingException
      ("Zebulun PresentResponse: bad BER form\n");
  }

  // Prepare to decode the components

  int num_parts = ber_cons.number_components();
  int part = 0;
  BEREncoding p;

  // Decoding: referenceId ReferenceId OPTIONAL

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun PresentResponse: incomplete");
  }
  p = ber_cons.elementAt(part);

  try {
    s_referenceId = new ReferenceId(p, true);
    part++; // yes, consumed
  } catch (ASN1Exception e) {
    s_referenceId = null; // no, not present
  }

  // Decoding: numberOfRecordsReturned NumberOfRecordsReturned

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun PresentResponse: incomplete");
  }
  p = ber_cons.elementAt(part);

  s_numberOfRecordsReturned = new NumberOfRecordsReturned(p, true);
  part++;

  // Decoding: nextResultSetPosition NextResultSetPosition

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun PresentResponse: incomplete");
  }
  p = ber_cons.elementAt(part);

  s_nextResultSetPosition = new NextResultSetPosition(p, true);
  part++;

  // Decoding: presentStatus PresentStatus

  if (num_parts <= part) {
    // End of record, but still more elements to get
    throw new ASN1Exception("Zebulun PresentResponse: incomplete");
  }
  p = ber_cons.elementAt(part);

  s_presentStatus = new PresentStatus(p, true);
  part++;

  // Remaining elements are optional, set variables
  // to null (not present) so can return at end of BER

  s_databaseOrDiagnosticRecords = null;

  // Decoding: databaseOrDiagnosticRecords Records OPTIONAL

  if (num_parts <= part) {
    return; // no more data, but ok (rest is optional)
  }
  p = ber_cons.elementAt(part);

  try {
    s_databaseOrDiagnosticRecords = new Records(p, true);
    part++; // yes, consumed
  } catch (ASN1Exception e) {
    s_databaseOrDiagnosticRecords = null; // no, not present
  }

  // Should not be any more parts

  if (part < num_parts) {
    throw new ASN1Exception("Zebulun PresentResponse: bad BER: extra data " + part + "/" + num_parts + " processed");
  }
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of the PresentResponse.
 *
 * @exception	ASN1Exception Invalid or cannot be encoded.
 * @return	The BER encoding.
 */

public BEREncoding
ber_encode()
       throws ASN1Exception
{
  return ber_encode(BEREncoding.UNIVERSAL_TAG, ASN1Sequence.TAG);
}

//----------------------------------------------------------------
/**
 * Returns a BER encoding of PresentResponse, implicitly tagged.
 *
 * @param tag_type	The type of the implicit tag.
 * @param tag	The implicit tag.
 * @return	The BER encoding of the object.
 * @exception	ASN1Exception When invalid or cannot be encoded.
 * @see asn1.BEREncoding#UNIVERSAL_TAG
 * @see asn1.BEREncoding#APPLICATION_TAG
 * @see asn1.BEREncoding#CONTEXT_SPECIFIC_TAG
 * @see asn1.BEREncoding#PRIVATE_TAG
 */

public BEREncoding
ber_encode(int tag_type, int tag)
       throws ASN1Exception
{
  // Calculate the number of fields in the encoding

  int num_fields = 3; // number of mandatories
  if (s_referenceId != null)
    num_fields++;
  if (s_databaseOrDiagnosticRecords != null)
    num_fields++;

  // Encode it

  BEREncoding fields[] = new BEREncoding[num_fields];
  int x = 0;

  // Encoding s_referenceId: ReferenceId OPTIONAL

  if (s_referenceId != null) {
    fields[x++] = s_referenceId.ber_encode();
  }

  // Encoding s_numberOfRecordsReturned: NumberOfRecordsReturned 

  fields[x++] = s_numberOfRecordsReturned.ber_encode();

  // Encoding s_nextResultSetPosition: NextResultSetPosition 

  fields[x++] = s_nextResultSetPosition.ber_encode();

  // Encoding s_presentStatus: PresentStatus 

  fields[x++] = s_presentStatus.ber_encode();

  // Encoding s_databaseOrDiagnosticRecords: Records OPTIONAL

  if (s_databaseOrDiagnosticRecords != null) {
    fields[x++] = s_databaseOrDiagnosticRecords.ber_encode();
  }

  return new BERConstructed(tag_type, tag, fields);
}

//----------------------------------------------------------------
/**
 * Returns a new String object containing a text representing
 * of the PresentResponse. 
 */

public String
toString()
{
  StringBuffer str = new StringBuffer("{");
  int outputted = 0;

  if (s_referenceId != null) {
    str.append("referenceId ");
    str.append(s_referenceId);
    outputted++;
  }

  if (0 < outputted)
    str.append(", ");
  str.append("numberOfRecordsReturned ");
  str.append(s_numberOfRecordsReturned);
  outputted++;

  if (0 < outputted)
    str.append(", ");
  str.append("nextResultSetPosition ");
  str.append(s_nextResultSetPosition);
  outputted++;

  if (0 < outputted)
    str.append(", ");
  str.append("presentStatus ");
  str.append(s_presentStatus);
  outputted++;

  if (s_databaseOrDiagnosticRecords != null) {
    if (0 < outputted)
    str.append(", ");
    str.append("databaseOrDiagnosticRecords ");
    str.append(s_databaseOrDiagnosticRecords);
    outputted++;
  }

  str.append("}");

  return str.toString();
}

//----------------------------------------------------------------
/*
 * Internal variables for class.
 */

public ReferenceId s_referenceId; // optional
public NumberOfRecordsReturned s_numberOfRecordsReturned;
public NextResultSetPosition s_nextResultSetPosition;
public PresentStatus s_presentStatus;
public Records s_databaseOrDiagnosticRecords; // optional

} // PresentResponse

//----------------------------------------------------------------
//EOF
